// Data 9 Sprin nyata, diambil persis dari SIANDI_Mockup_v3.html (halaman Daftar Sprin).
// Akan diganti query Supabase asli di tahap "sambungkan data asli".
export const DAFTAR_SPRIN_CONTOH = [
  {
    nomor: 'Sprin/368/II/OPS.1.3./2026',
    perihal: 'Operasi Kepolisian Pekat I Lodaya 2026',
    jenis: 'OPERASI KEPOLISIAN KEWILAYAHAN',
    waktu: '21 Feb 2026 – 2 Mar 2026 · tanpa apel tunggal',
    personel: 44,
    kelompok: 17,
    status: 'Terbit',
  },
  {
    nomor: 'Sprin/535/III/OPS.1.2.3./2026',
    perihal: 'Pengamanan Hari Raya Idul Fitri 1447 H',
    jenis: 'OPERASI KEPOLISIAN HARI BESAR',
    waktu: '13 Mar 2026 – 25 Mar 2026 · tanpa apel tunggal',
    personel: 617,
    kelompok: 43,
    status: 'Terbit',
  },
  {
    nomor: 'Sprin/1421/VI/PAM.2.2./2026',
    perihal: 'Pengamanan Kedatangan Wakapolri ke Wilkum Polres Cimahi',
    jenis: 'PENGAMANAN VIP/VVIP',
    waktu: '20 Jun 2026 · apel 15:00',
    personel: 104,
    kelompok: 17,
    status: 'Terbit',
  },
  {
    nomor: 'Sprin/1491/VII/PAM.2.2./2026',
    perihal: 'Pengamanan Kunjungan Kerja Kapolri ke Sespim Lemdiklat Polri',
    jenis: 'PENGAMANAN VIP/VVIP',
    waktu: '2 Jul 2026 – 3 Jul 2026 · apel 09:00',
    personel: 315,
    kelompok: 20,
    status: 'Terbit',
  },
  {
    nomor: 'Sprin/1600/VII/PAM.3.2./2026',
    perihal: 'Pengamanan Aksi Unjuk Rasa Aliansi SP/SB Kota Cimahi',
    jenis: 'PENGAMANAN UNJUK RASA',
    waktu: '23 Jul 2026 · apel 09:00',
    personel: 242,
    kelompok: 40,
    status: 'Terbit',
  },
  {
    nomor: 'Sprin/1605/VII/PAM.1.3.2./2026',
    perihal: 'Kegiatan Rutin yang Ditingkatkan / Patroli dan Razia Skala Besar',
    jenis: 'KEGIATAN RUTIN YANG DITINGKATKAN',
    waktu: '25 Jul 2026 · apel 21:00',
    personel: 54,
    kelompok: 15,
    status: 'Terbit',
  },
  {
    nomor: 'Sprin/1686/VII/PAM.1.3.2./2026',
    perihal: 'Kegiatan Rutin yang Ditingkatkan / Patroli dan Razia Skala Besar',
    jenis: 'KEGIATAN RUTIN YANG DITINGKATKAN',
    waktu: '26 Jul 2026 · apel 21:00',
    personel: 35,
    kelompok: 6,
    status: 'Terbit',
  },
  {
    nomor: 'Sprin/1694/VII/PAM.3.2./2026',
    perihal: 'Pengamanan Keberangkatan Massa KC FSPMI dan DPC SPN ke Kemendagri Jakarta',
    jenis: 'PENGAMANAN UNJUK RASA',
    waktu: '28 Jul 2026 · apel 05:30',
    personel: 28,
    kelompok: 12,
    status: 'Terbit',
  },
  {
    nomor: 'Sprin/1702/VII/PAM.3.2./2026',
    perihal: 'Pengamanan Aksi Unjuk Rasa Koalisi 7 SP-SB Kab. Bandung Barat',
    jenis: 'PENGAMANAN UNJUK RASA',
    waktu: '30 Jul 2026 · apel 08:00',
    personel: 86,
    kelompok: 10,
    status: 'Terbit',
  },
]

export const STATUS_BADGE_STYLE = {
  Terbit: { backgroundColor: '#E8F5EE', color: '#1F7A4D' },
  Menunggu: { backgroundColor: '#FDF6E3', color: '#8A6100' },
  Dikembalikan: { backgroundColor: '#FDECEA', color: '#B3261E' },
}
